from colorama import Fore, Back, Style
from colorama import init
init()
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.WHITE)
print("https://vk.com/topgog666 Узнайте реальное имя этого человека (Олег это выдуманное)")
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)

print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

