from colorama import Fore, Back, Style
from colorama import init
init()
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.WHITE)
print("https://www.youtube.com/channel/UCnvziEmoKHOi4X9um0ydKBg Почему я выбрал этот канал для квеста?")
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)

print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)
print(Fore.BLACK)

